name: Generate Datas
on:
  schedule: # At minute 0 on every day-of-month. Taken from: https://crontab.guru/#0_*_*/1_*_*
    - cron: "0 * */1 * *"
  workflow_dispatch:
jobs:
  build:
    name: Jobs to update datas
    runs-on: ubuntu-latest
    steps:
      # Snake Animation
      - uses: Platane/snk@master
        id: snake-gif

        with:
          github_user_name: Akamiz96
          svg_out_path: dist/github-contribution-grid-snake.svg
      - uses: crazy-max/ghaction-github-pages@v2.1.3
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
